language: python
python:
  - "3.7"
branch: gh-pages
install:
  - pip install -r requirements.txt
script:
  - bash ./push.sh
deploy:
  provider: pages
  skip_cleanup: true
  email: sean.davey@tieto.com
  name: 'Sean Davey'
  github_token: $github_token
  on:
    branch: gh-pages
