language: python
python:
  - "3.7"
branch: gh-pages
on:
  branch: gh-pages
# command to install dependencies
install:
  - pip install -r requirements.txt
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $LUNCH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: gh-pages
script:
  - bash ./push.sh

